services:
  - type: web
    name: cefr-master
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATA_DIR
        value: /var/data
      - key: UPLOADS_DIR
        value: /var/data/uploads
